### ISSUE TITLE
CSD PDF output is producing blank output?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cc#30]
Is this the case @opoudjis ? Can you help confirm? Thanks!

**Comment by ronaldtse** [comment]
This is the line: https://github.com/riboseinc/asciidoctor-csd/blob/b035722baf4bec5de7c4c6392ab6453f815cf93e/lib/metanorma/csd/processor.rb#L35

**Comment by opoudjis** [comment]
Well, the pdf generator embedded in the asciidoctor class still works fine. So your implementation in metanorma is what is buggy. Debugging.

**Comment by opoudjis** [comment]
Got it. The filename URL used with Chromium has to be the absolute URL of the file location, Chromium does not understand relative links. So not file://rice.pdf.html, but file:///Users/nickn/Documents/Arbeit/upwork/ribose/asciidoctor-csd/spec/examples .

Which is why my code had `url = "#{Dir.pwd}/#{filename}.html"`

**Comment by opoudjis** [comment]
Fixed in metanorma gem, bumped version, made metanorma a gem dependency for asciidoctor-csd.
