### ISSUE TITLE
(URGENT) IETF RFC/Internet-Draft references are not "in a collection of RFCs"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cc#337]
Source:
```
[bibliography]
== Normative references

* [[[RFC5545,IETF RFC 5545]]]
* [[[RFC5988,IETF RFC 5988]]]
```

Notice the "In: RFC" line. This should not be there.

<img width="845" alt="Screenshot 2024-12-08 at 10 15 07 PM" src="https://github.com/user-attachments/assets/7622f292-3ebb-4969-8791-e9bb100547f1">

Actually it also happens with other types of standards:
<img width="845" alt="image" src="https://github.com/user-attachments/assets/a16ffe2f-1387-42ad-bedb-7a6a798c507c">

I don't know if this issue occurs in other flavors but certainly in CalConnect.

**Comment by opoudjis** [comment]
relaton-render quite reasonably has:

````
{{ labels['in'] | capitalize }}:_{{ series_title }}.
````

If something is marked up as a series in the bibliography, then it will say that the citation is part of that series.

As it turns out, we have marked up IETF references as belonging to an RFC series ("series: RFC, number: 5545"), and W3C too.

Rather than get into a negotiation about which series we do and which series we don't annotate in the bibliography, I'll just drop series from standards citations: they will routinely run into this issue.

**Comment by opoudjis** [comment]
My update to relaton-render is being ignored locally, even after restart. I am caching templates with singleton, but a restart should have taken care of that.

**Comment by opoudjis** [comment]
Ah, it was being overridden in isodoc.

**Comment by opoudjis** [comment]
We need to retain series in NIST, as it is critical to how NIST references are rendered; it is the full series there, not just the title.

**Comment by opoudjis** [comment]
You will need to pull isodoc to make this work.
