### ISSUE TITLE
(URGENT) Remove "viewed: xxx" from all normative references

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cc#338]
We should remove "viewed: xxx" from all normative references.
This is inappropriate as all normative references are meant to be uniquely identifiable and accessible content. This is different from citing a website where it will change the next day.

<img width="858" alt="Screenshot 2024-12-08 at 10 18 07 PM" src="https://github.com/user-attachments/assets/e9a21fbf-7ca1-44d5-a9b2-f9b5417cf4e2">

**Comment by opoudjis** [comment]
CC is inheriting its template from the relaton-render default.

The rule you are proposing of normative references not having viewed dates for URIs is NOT practice in the major style guides, which put viewed dates on every single URI nominated for a resource, as a blanket rule. The "trust me bro, standards bodies will keep their URIs stable" sentiment is not one I am comfortable implementing as default behaviour for relaton-render.

OTOH, Chicago makes an exception for "citations of formally published electronic sources", such as academic articles (which have the same rationale as standards that you give): https://camosun.libguides.com/Chicago-17thEd/onlineArticles . MLA does not make that distinction: https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_formatting_and_style_guide/mla_works_cited_electronic_sources.html and neither does Mouton/De Guyter, who I proofread for.

There is clearly variable practice out there, as Chicago acknowledges, but it is also more common to insert the date accessed universally than not. Rather than get bogged down in yet another argument, I will take the dates accessed out of the default template for articles, monographs, and standards, and I will document in the readme that these may need to be put back in for specific flavours.
